### ISSUE TITLE
ios留言板夜間模式不完全

### ISSUE THREAD

**Issue by Max-ZGao** [wanglin2021/report#10]
ios通过safari设置夜间模式并访问留言板，评论的评论背景为白色。

https://manhuabika.com/pcomments/?cid=5822a6e3ad7ede654696e482&ishide=999

ios版本14.8.1

**Comment by wanglin2021** [comment]
![image](https://user-images.githubusercontent.com/101633772/192678878-022b5552-8355-4902-a213-228ff5683a59.png)
您好 我這邊看是完全進入夜間模式的 
您是指填寫評論的input box 沒有進入夜間模式嗎？

**Comment by wanglin2021** [comment]
![image](https://user-images.githubusercontent.com/101633772/192679064-d0c1138d-ba8b-483e-8197-3d1031eefd15.png)
大概像是這樣？

**Comment by Max-ZGao** [comment]
不是input box。留言下其他用户的评论，类似这样
![image](https://user-images.githubusercontent.com/57144940/192682860-60b55f32-9943-4e17-9025-8ce04e1d7998.jpeg)

**Comment by wanglin2021** [comment]
![image](https://user-images.githubusercontent.com/101633772/192683830-81a7399c-d26a-4f7c-a7c5-e75cd58b59cb.png)

![image](https://user-images.githubusercontent.com/101633772/192683861-e61fcd1e-4df7-4a44-8263-ac3052d5784c.png)

您好，非常感謝您的反饋 
我已經對其進行了修復
并且推送更新
您可以刷新頁面查看新的效果
再次感謝您的反饋，有問題請隨時聯係我
