### ISSUE TITLE
先后打开个人中心时会出现其他人的ID

### ISSUE THREAD

**Issue by zhaoyunlong1** [wanglin2021/report#11]
[进入首页或分类后打开个人中心，可能会出现个人中心显示其他人ID的情况。 
![IMG_0661](https://user-images.githubusercontent.com/77422611/192726267-dd3bae32-10ca-4394-a95d-bfd925a99f22.jpeg)
![IMG_0660](https://user-images.githubusercontent.com/77422611/192726310-d7d3d3e9-c908-4521-8b0f-e80d969f275f.jpeg)
![IMG_0659](https://user-images.githubusercontent.com/77422611/192726460-60c63d45-5f87-489f-a0cd-e358a8f6885d.jpeg)

西瓜是我的账号。ipadOS15.7

**Comment by wanglin2021** [comment]
疑似緩存命中異常 正在排查

**Comment by wanglin2021** [comment]
已經調整命中規則 
目前在我這邊無法復現bug 
如果可能希望您幫忙再試一下

**Comment by zhaoyunlong1** [comment]
我这里没有再出现这个情况了

**Comment by wanglin2021** [comment]
再次感謝您的反饋，有問題請隨時聯係我。
