### ISSUE TITLE
账户异常无法登录

### ISSUE THREAD

**Issue by kele1732** [wanglin2021/report#12]
账号：a1732661522
![image](https://user-images.githubusercontent.com/114570023/192732351-b9ce9e85-0573-41e1-8c2c-3ad5cd5258b8.png)

**Comment by wanglin2021** [comment]
您是否最近在留言板發表過評論？service下發了無效的token

**Comment by wanglin2021** [comment]
您可以telegram聯係我

**Comment by wanglin2021** [comment]
https://t.me/Sirin1234567

**Comment by kele1732** [comment]
抱歉，我不太清楚自己發表了些什麼，只是沒有警告和提示然後賬號就如同被封了一樣……，可能是無心之舉發了無關內容吧，希望能幫忙恢復一下，感謝。&nbsp;


可乐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月28日(星期三) 下午4:47
收件人: "wanglin2021/report";
抄送: "Author";
主题: Re: [wanglin2021/report] 账户异常无法登录 (Issue #12)





 
您是否最近在留言板發表過評論？service下發了無效的token
 
&mdash;
