### ISSUE TITLE
无法接受Cookies&用户协议，和无法点击登录按键

### ISSUE THREAD

**Issue by XxxxHDxxxX** [wanglin2021/report#13]
机型：iPhone 8 Plus
系统版本：iOS 13.6.1
软件版本：IOS輕量版
网络：Wi-Fi
运营商：电信
是否使用VPN（全局模式）：是
具体操作过程：Safari浏览器进入登录界面后无法接受cookies&用户协议,更换谷歌浏览器之后能接受了但是无法点登录键

**Comment by wanglin2021** [comment]
ios14- 移除cookies box 
增加ios version 判斷
低於14啓動兼容模式，使用原生alert完成用戶提示

**Comment by wanglin2021** [comment]
驗證通過，IOS 13兼容
