### ISSUE TITLE
UC浏览器没有视频

### ISSUE THREAD

**Issue by ddddeddf** [wanglin2021/report#4]
UC浏览器没有打开视频的窗口

**Comment by ddddeddf** [comment]
@wanglin2021

**Comment by wanglin2021** [comment]
> @wanglin2021

感謝您反饋 請至少提供一個無法播放的網址 謝謝

**Comment by wanglin2021** [comment]
您好 我發現uc borower 不支持 document.onload事件，我正在認真思考怎麽解決這個問題

**Comment by wanglin2021** [comment]
> @wanglin2021

久等了 這個問題已經得到了修復
感謝您的反饋，有問題請隨時聯係我
